{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-spa-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  production.json: |
    {
      "CONSOLE_API": {
        "ENDPOINT": "{{ .Values.console_api }}"
      },
      "VUE_APP_API": {
        "ENDPOINT": "{{ .Values.console_api }}"
      },
      "GTAG_ID": "DISABLED",
      "NO_SERVER_MODE": false
    }
{{- end }}
